#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

set -e

[[ -n "$PAKITHEME_VERBOSE" ]] && set -x ||:

usage() {
  echo 'usage: pakitheme install-system|install-user|clear-cache [<theme>]'
}

die() {
  echo "$@" >&2
  exit 1
}

if [[ -z "$1" || "$1" == "-h" || "$1" == "--help" ]]; then
  usage
  exit
fi

cache_home="${XDG_CACHE_HOME:-$HOME/.cache}"
data_home="${XDG_DATA_HOME:-$HOME/.local/share}"
pakitheme_cache="$cache_home/pakitheme"
repo_dir="$pakitheme_cache/repo"

case "$1" in
install-system) install_target=system ;;
install-user) install_target=user ;;
clear-cache) rm -rf "$pakitheme_cache"; exit ;;
*) usage; exit 1 ;;
esac

[[ -n "$2" ]] && theme=$2 || \
  theme=$(gsettings get org.gnome.desktop.interface gtk-theme | tr -d "'")
echo "Converting theme: $theme"

app_id=org.gtk.Gtk3theme.$theme

for location in "$data_home/themes" "$HOME/.themes" /usr/share/themes; do
  if [[ -d "$location/$theme" ]]; then
    echo "Found theme located at: $location/$theme"
    theme_path="$location/$theme"
    break
  fi
done

[[ -n "$theme_path" ]] || die 'Could not locate theme.'

bundles=()

while read -r version; do
  build_dir="$pakitheme_cache/$theme-$version"
  bundle="$pakitheme_cache/$theme-$version.flatpak"

  rm -rf "$build_dir"
  flatpak build-init --type=extension "$build_dir" $app_id org.freedesktop.Platform \
    org.freedesktop.Platform "$version"

  for theme_subdir in "$theme_path/gtk-3.0" "$theme_path/gtk-3.22"; do
    if [[ -d "$theme_subdir" ]]; then
      cp -a "$theme_subdir"/* "$build_dir/files"
      copied=1
    fi
  done

  if [[ -z "$copied" ]]; then
    die "Theme directory did not contain any recognized GTK themes."
  fi

  mkdir -p "$build_dir/files/share/appdata"
  cat >"$build_dir/files/share/appdata/$app_id.appdata.xml" <<EOF
  <?xml version="1.0" encoding="UTF-8"?>
  <component type="runtime">
    <id>$app_id</id>
    <metadata_license>CC0-1.0</metadata_license>
    <name>$name Gtk theme</name>
    <summary>$name Gtk theme (generated via pakitheme)</summary>
  </component>
EOF

  appstream-compose --prefix="$build_dir/files" --basename=$app_id --origin=flatpak $app_id

  ostree --repo="$repo_dir" init --mode=archive
  ostree --repo="$repo_dir" config set core.min-free-space-percent 0

  flatpak build-finish "$build_dir"
  flatpak build-export "$repo_dir" "$build_dir" 3.22
  flatpak build-bundle --runtime "$repo_dir" "$bundle" "$app_id" 3.22
  trap 'rm "$bundle"' EXIT

  bundles+=("$bundle")

  # flatpak install -y --$install_target "$bundle"
done < <(flatpak list --$install_target --columns=application:f,branch:f | \
         awk '/org\.freedesktop\.Platform\s/{print $2;}')

for bundle in "${bundles[@]}"; do
  flatpak install -y --$install_target "$bundle"
done
